SET EDITOR_FOLDER=C:\Program Files (x86)\ConTEXT
SET EDITOR_EXECUTABLE=ConTEXT.exe
SET DEFT_DSK_FOLDER=C:\CODING\TRSCOLOR\DeftPascal
SET DEFT_DSK_FILE=deft.dsk
SET DEFT_PROJECTS_FOLDER=C:\CODING\TRSCOLOR\DeftPascal\Projects
SET MAME_FOLDER=C:\CODING\TRSCOLOR\mame0196b_64bit
SET MAME_SPEED=9.0
SET AUTOIT_FOLDER=C:\Program Files (x86)\AutoIt3
